# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: ''

podAnnotations: {}

nameOverride: subsea-x-app

env:
  - name: PORT
    value: '3000'

  # livenessProbe:
  #   httpGet:
  #     path: "/"
  #     port: 8080
  #   initialDelaySeconds: 15
  #   periodSeconds: 30
  #   failureThreshold: 5

  # readinessProbe:
  #   httpGet:
  #     path: "/"
  #     port: 8080
  #   successThreshold: 1
  #   failureThreshold: 5


securityContext:
  runAsUser: 1001
  runAsGroup: 1001

  
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

ingress:
  enabled: false

resources:
  limits:
    cpu: 350m
    memory: 750Mi
  requests:
    cpu: 200m
    memory: 512Mi


tolerations: []

affinity: {}

serviceAccount:
  create: false
  annotations: {}
  name: ''
